### ISSUE TITLE
Close single tab with mouse

### ISSUE THREAD

**Issue by freevryheid** [nim-lang/Aporia#109]
Nice editor - been looking to replace st3.  

Clicking the close [x] button on a tab doesn't close it when it is the only tab. Ctrl-w works OK and closing with multiple tabs works  OK.

**Comment by achesak** [comment]
What is the expected behaviour for closing the last tab? Should it be allowed or not? As @freevryheid said, Ctrl+W works, but the close button does not. The close button is an easy fix, but trying to use any other feature (save, find, undo, etc) when there is no file open causes aporia to crash.

Should the ability to close the last tab though Ctrl+W be removed, or should everything else be given a check to see if any files are open currently?

**Comment by dom96** [comment]
The ability to close the last tab via Ctrl+W should be removed.
