### ISSUE TITLE
Mac OS: could not import: iconv_open

### ISSUE THREAD

**Issue by brezenix** [nim-lang/Aporia#69]
Hi!
I compiled source according to instructions.
After ./aporia I got error: could not import: iconv_open
After this I installed libiconv (1.14).
But I get the same error.
What I need else for running Aporia on Mac OS?

**Comment by dom96** [comment]
Did you install GTK?

**Comment by brezenix** [comment]
Yes, I did. gtk+-2.24.25 already installed

**Comment by dom96** [comment]
I think that libiconv is a gtk dependency, perhaps you need a specific version. I'm afraid I can't be of much help as I don't have a Mac.

**Comment by aboisvert** [comment]
I'm having the same issue.  GTK+ installed (via macports), libiconv also installed.  Same error as @brezenix

**Comment by aboisvert** [comment]
This change to nim's standard library bindings fixed it for me:

diff --git a/lib/pure/encodings.nim b/lib/pure/encodings.nim
index 958a413..d401c4d 100644
--- a/lib/pure/encodings.nim
+++ b/lib/pure/encodings.nim
@@ -262,7 +262,7 @@ else:
   else:
     const iconvDll = "(libc.so.6|libiconv.so)"
 
-  when defined(macosx) and defined(powerpc):
+  when defined(macosx):
     const prefix = "lib"
   else:
     const prefix = ""

**Comment by dom96** [comment]
Could you create a PR for this on the Nim repo?

**Comment by dom96** [comment]
Fixed via https://github.com/Araq/Nim/issues/2831

**Comment by oderwat** [comment]
I just tripped over this change. Afaik OP had a non system libiconv.dylib in his path. It seems like at least since 10.8.4 there is no "lib" prefix in the system supplied libiconv (/usr/lib/libiconv.dylib). I just created a PR https://github.com/nim-lang/Nim/pull/3490 to remove the prefix but it may be better to go back to the powerpc case. Even if probably nobody using nim will use powerpc anymore or will use a newer libiconv in that case anyway.
